### PR TITLE
Update generateTime.ts

### PR DESCRIPTION
**Pull request by kevin-gaffney-epam**
Hello @SherAtrium

I have been giving your app to my team members for a while now.  I love it.  

I do see a bug in how it handles the noon hours on 12 hr setting.  Instead of 12 it says 00.  I added an if to account for this.  I hope you don't mind.  Also, I was getting an undefined error when setting times across midnight.  Accounted for this too.

Hope this helps,
Kevin Gaffney
Kevin_gaffney@epam.com

### CODE REVIEW

**Comment by SherAtrium** [comment]
Hello @kevin-gaffney-epam,
I am not in EPAM anymore and I am not contributing to this project that's why I am answering you with some delay sorry for that. Feel free to change functionality and fix bugs. I am totally okay with your PR.

**Review by SheratriumEPAM — APPROVED** [review]

**Comment by SheratriumEPAM** [comment]
> great, thanks! Who can I reach for a second review?

I am not sure, to be honest. But, I can merge this PR by myself if you finished working on that.

**Comment by SheratriumEPAM** [comment]
Or, you can reach @ArturSalikhovEPAM or @zahhar. They are also maintainers.

**Comment by kevin-gaffney-epam** [comment]
I am finished.  merge when you have time

**Pull request merged**
